// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpshabdqjxaxiapwtgax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhwc2hhYmRxanhheGlhcHd0Z2F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMjQyMjgsImV4cCI6MjA2MzgwMDIyOH0.tV4k-KaY0lwEj-tOK0k9_6bTxVErasW3IEEIwHQs0T0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);